### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by lclarksl**

### CODE REVIEW

**Comment by csscottlogic** [comment]
Just out of interest, what sort of warnings does this PR address? Has this come out of the introduction of ES linting?

**Comment by lclarksl** [comment]
The majority are missing declarations of types of properties passed to components. A few were imports that were never used.

**Comment by ianlovell** [comment]
:shipit:

**Comment by csscottlogic** [comment]
Thanks for the explanation. :shipit:

**Pull request merged**
